version: '3'

services:


  bioniq-formulas:
    build:
      context: ./
      dockerfile: ./Dockerfile
    container_name: bioniq-formulas
    #entrypoint: ["/code/entrypoint.sh"]
    command: python /code/manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
        #    env_file:
        #      - .env.medical-analytics
    depends_on:
      - bioniq-formulas-db
